name: test

on:
  pull_request:

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - run:
          go test ./...
